### ISSUE TITLE
[1.12.2] [1.0.1] Suggestions

### ISSUE THREAD

**Issue by wamc2017** [DoctorFTB/ThaumicTerminal#1]
Hi,

tried your mod and the terminal is working fine so far, but I have a few suggestions:
- Clicking store items, stores the vis crystals, not the content of the crafting grid, should be the other way around
- there should be some way to attach a workbench charger to the me system, maybe some kind of interface
- It would be nice, if the terminal allows to show the aspects from items inside the system, when pressing shift
- Would be nice if the terminal adds support for Thaumic JEI, so the recipes could be shift clicked to craft
- The recipe for the terminal should be an Arcane Workbench recipe, which requires vis crystals, instead a normal crafting recipe

Thanks for looking into it. :)

Best regards,
wamc

**Comment by DoctorFTB** [comment]
About "Clicking store items, stores the vis crystals, not the content of the crafting grid, should be the other way around" - Fixed.
About "The recipe for the terminal should be an Arcane Workbench recipe, which requires vis crystals, instead a normal crafting recipe" - Say your variant for recipe.
About other - //TODO.

**Comment by wamc2017** [comment]
> Say your variant for recipe.

Hmm, how about 2 of each crystals and 200 vis?

> I fix only in my terminal.

That's ok, I think the other terminals have to be fixed on AE2s side...
