### ISSUE TITLE
Cant complete aggression module when using thaumic jei integration.

### ISSUE THREAD

**Issue by garyyo** [DoctorFTB/ThaumicTerminal#10]
I am trying to craft an aggression modulel. I have all the items available in my inventory and am clicking the jei complete plus button to move the crafting recipe into the window. instead it puts two grey glass panes (which are in the ae system) and doesnt complete anymore of the recipe.

**Comment by DoctorFTB** [comment]
Try 1.0.9 version.

**Comment by garyyo** [comment]
works but i tested it earlier on a server, which is now down. 

probably fine though.
