### ISSUE TITLE
recipe is able to be crafted until you close the terminal and open it again

### ISSUE THREAD

**Issue by garyyo** [DoctorFTB/ThaumicTerminal#11]
after using the recipe completion the recipe is not immediately craftable. it refuses to let you craft it. a fix to this is to close the terminal and open it again. this allows you pull the item out of the crafting window. this affects both vanilla crafting recipes and arcane crafting.

**Comment by DoctorFTB** [comment]
Hmm. Not correct understand question.
My tests: 
https://gyazo.com/53c006f220a373e5ad95466ca83b8827
https://gyazo.com/a6d414c849060ced2736b283a3304e39
Can u make video/gif?

**Comment by garyyo** [comment]
this also works now for me with the new version. but again i previously did this on a server, so that might be the issue.
