### ISSUE TITLE
[Suggestion] Add Shift+Click

### ISSUE THREAD

**Issue by Xobra** [DoctorFTB/ThaumicTerminal#12]
If you Shift Click onto Crystals, they automatically go into their slots in the normal Arcane Table; would be nice of this could work for the Terminal too. Or add an Auto Extract into these Slots from the AE System itself.

**Comment by DoctorFTB** [comment]
Try 1.0.10 version.

**Comment by DoctorFTB** [comment]
@Xobra

**Comment by Xobra** [comment]
Working fine
