### ISSUE TITLE
ME Crafting UI Crashes

### ISSUE THREAD

**Issue by osa519** [DoctorFTB/ThaumicTerminal#2]
When trying to craft something through the terminal using the auto crafting features of ME, the game crashes with
Description: Rendering screen
Error 
[crash-2018-07-23_17.46.03-client.txt](https://github.com/DoctorFTB/ThaumicTerminal/files/2221346/crash-2018-07-23_17.46.03-client.txt)

**Comment by DoctorFTB** [comment]
Thanks for report.
Fix in 1.0.4 version.
