### ISSUE TITLE
1.0.5 marked for 1.12.1

### ISSUE THREAD

**Issue by xbony2** [DoctorFTB/ThaumicTerminal#4]
Can you mark [this](https://minecraft.curseforge.com/projects/thaumic-terminal/files/2590926) as for Minecraft 1.12.2? Almost no one is using 1.12.1 as far as I know. You can/should mark files as for 1.12, 1.12.1, and 1.12.2, which I believe you can do.

**Comment by DoctorFTB** [comment]
Changed to 1.12.2.

**Comment by xbony2** [comment]
thanks 👍
