### ISSUE TITLE
Compatibility with JEI and thaumic JEI

### ISSUE THREAD

**Issue by garyyo** [DoctorFTB/ThaumicTerminal#8]
There is no recipe completion compatibility with JEI and Thaumic JEI. The terminal itself is quite useless when its easier to just gather materials and walk over to the table to quickly make all the items. 

More important is that it cannot be used as a replacement for a normal crafting terminal because mundane crafting recipes don't get completed either.

**Comment by DoctorFTB** [comment]
In progress..

**Comment by DoctorFTB** [comment]
@garyyo Hi.
Integration with JEI & Thuamic JEI created.
Could you check integration.
May be bugs/not correct working/ideas.

P.S. Sorry, but u Russian, right?

**Comment by garyyo** [comment]
the integration works wonderfully. thank you

I am russian, yes. the name kinda gives it away.

**Comment by DoctorFTB** [comment]
No problem.
If u have any ideas - !please! create issue with ur idea!

P.S. Давай больше репортов с идеями, а то хз, что делать. xD

**Comment by garyyo** [comment]
I have a few ideas but they might be outside the scope of the project. I will write them up in seperate issues in a bit.
