### ISSUE TITLE
Golem provider seal capability

### ISSUE THREAD

**Issue by garyyo** [DoctorFTB/ThaumicTerminal#9]
Currently there is several things that you can do with the provider seal in thaumcraft. they can allow golems to take items from inventories and provide them to other seals, or if the "Golem logistics" research is completed, allow a player to request from these inventories. In Applied energistics putting a storage bus on an interface exposes the items on the interfaces side to the storage bus's side (allowing for mass item storage with minimal channel use). 

I propose to think of a provider seal as a sort of storage bus for golems and to add a new "golem interface" that would allow golems to have exposure to the whole ME system for things like provider seals (or empty). i would imagine it would be able to also take a crafting card to be able to craft things that golems request, but I don't know how feasible this is. This way you could be able to have a magically "wireless" access to your ME system, in which golems retrieve items for you.

this might be more appropriate for a general thaumcraft-AE2 bridge mod (that I would name thaumic energistics but that name is taken by a 1.7 mod).

**Comment by DoctorFTB** [comment]
Mod ThaumicEnergistics have official port.
Check: https://github.com/Nividica/ThaumicEnergistics/issues/344

**Comment by garyyo** [comment]
oh, well thanks i hadnt heard the news.
